<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" total="3" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="354" started-at="2022-06-05T18:05:23Z" finished-at="2022-06-05T18:05:23Z">
    <groups>
      <group name="regression">
        <method signature="sample1AdactinMainpage.Test3()[pri:1, instance:org.gropingss.sample1AdactinMainpage@4566e5bd]" name="Test3" class="org.gropingss.sample1AdactinMainpage"/>
      </group> <!-- regression -->
      <group name="smoke">
        <method signature="sample1AdactinMainpage.Test1()[pri:0, instance:org.gropingss.sample1AdactinMainpage@4566e5bd]" name="Test1" class="org.gropingss.sample1AdactinMainpage"/>
        <method signature="sample1AdactinMainpage.Test2(java.lang.String, java.lang.String)[pri:-2, instance:org.gropingss.sample1AdactinMainpage@4566e5bd]" name="Test2" class="org.gropingss.sample1AdactinMainpage"/>
      </group> <!-- smoke -->
      <group name="sanity">
        <method signature="sample1AdactinMainpage.Test1()[pri:0, instance:org.gropingss.sample1AdactinMainpage@4566e5bd]" name="Test1" class="org.gropingss.sample1AdactinMainpage"/>
      </group> <!-- sanity -->
      <group name="retest">
        <method signature="sample1AdactinMainpage.Test3()[pri:1, instance:org.gropingss.sample1AdactinMainpage@4566e5bd]" name="Test3" class="org.gropingss.sample1AdactinMainpage"/>
      </group> <!-- retest -->
    </groups>
    <test name="Test" duration-ms="354" started-at="2022-06-05T18:05:23Z" finished-at="2022-06-05T18:05:23Z">
      <class name="org.gropingss.sample1AdactinMainpage">
        <test-method status="FAIL" signature="Test2(java.lang.String, java.lang.String)[pri:-2, instance:org.gropingss.sample1AdactinMainpage@4566e5bd]" name="Test2" duration-ms="0" started-at="2022-06-05T23:35:23Z" data-provider="login" finished-at="2022-06-05T23:35:23Z">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
Method private void org.gropingss.sample1AdactinMainpage.Test2(java.lang.String,java.lang.String) throws java.lang.InterruptedException requires a @DataProvider named : login]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
Method private void org.gropingss.sample1AdactinMainpage.Test2(java.lang.String,java.lang.String) throws java.lang.InterruptedException requires a @DataProvider named : login
	at org.testng.internal.Parameters.findDataProvider(Parameters.java:263)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:425)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1253)
	at org.testng.internal.Invoker.createParameters(Invoker.java:980)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1070)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:753)
	at org.testng.TestRunner.run(TestRunner.java:607)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:368)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:363)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:321)
	at org.testng.SuiteRunner.run(SuiteRunner.java:270)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1284)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1209)
	at org.testng.TestNG.runSuites(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1096)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test2 -->
        <test-method status="FAIL" signature="Test1()[pri:0, instance:org.gropingss.sample1AdactinMainpage@4566e5bd]" name="Test1" duration-ms="163" started-at="2022-06-05T23:35:23Z" finished-at="2022-06-05T23:35:23Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at org.openqa.selenium.support.pagefactory.DefaultElementLocator.findElement(DefaultElementLocator.java:69)
	at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:38)
	at com.sun.proxy.$Proxy9.getTagName(Unknown Source)
	at org.openqa.selenium.support.ui.Select.<init>(Select.java:45)
	at org.base.BaseClassAdactin.selectByIndex(BaseClassAdactin.java:88)
	at org.gropingss.sample1AdactinMainpage.Test1(sample1AdactinMainpage.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1137)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:753)
	at org.testng.TestRunner.run(TestRunner.java:607)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:368)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:363)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:321)
	at org.testng.SuiteRunner.run(SuiteRunner.java:270)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1284)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1209)
	at org.testng.TestNG.runSuites(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1096)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test1 -->
        <test-method status="FAIL" signature="Test3()[pri:1, instance:org.gropingss.sample1AdactinMainpage@4566e5bd]" name="Test3" duration-ms="30" started-at="2022-06-05T23:35:23Z" finished-at="2022-06-05T23:35:23Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at org.openqa.selenium.support.pagefactory.DefaultElementLocator.findElement(DefaultElementLocator.java:69)
	at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:38)
	at com.sun.proxy.$Proxy9.sendKeys(Unknown Source)
	at org.base.BaseClassAdactin.SendKeys(BaseClassAdactin.java:44)
	at org.gropingss.sample1AdactinMainpage.Test3(sample1AdactinMainpage.java:69)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1137)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:753)
	at org.testng.TestRunner.run(TestRunner.java:607)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:368)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:363)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:321)
	at org.testng.SuiteRunner.run(SuiteRunner.java:270)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1284)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1209)
	at org.testng.TestNG.runSuites(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1096)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test3 -->
      </class> <!-- org.gropingss.sample1AdactinMainpage -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
